// Forel - A native macOS file-automation app
// Copyright (C) 2026  Lab421
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

/// Noise generated by the OS or other apps, never something a rule should
/// see: Finder's folder metadata cache, AppleDouble resource forks (common
/// on network/exFAT volumes), and Microsoft Office's lock files for an open
/// document. Shared by the watcher and the Dry Run/Run Now folder scan so
/// all three execution paths agree on what's visible.
enum SystemFileFilter {
    static func isExcluded(_ filename: String) -> Bool {
        filename == ".DS_Store" || filename.hasPrefix("._") || filename.hasPrefix("~$")
    }
}
